use base64::Engine;
use std::fs;
use std::time::{SystemTime, UNIX_EPOCH};

/// Decode base64 media (generated by an agent tool call) and write it to a
/// workspace-relative path. Kept separate from write_file because the
/// content here is binary, not UTF-8 text.
#[tauri::command]
pub fn write_file_binary(
    workspace: String,
    path: String,
    base64_content: String,
) -> Result<(), String> {
    let p = crate::resolve(&workspace, &path)?;
    crate::ensure_not_workspace_root(&workspace, &p)?;
    if let Some(parent) = p.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_content.trim())
        .map_err(|e| e.to_string())?;
    fs::write(p, bytes).map_err(|e| e.to_string())
}

/// Decodes a base64 image and writes it to the OS temp directory, returning
/// the absolute path — used when the active provider/model can't accept
/// image content directly in chat messages (see agent.ts's supportsVision
/// gating), so the path can be handed to a vision-capable MCP tool instead.
#[tauri::command]
pub fn save_temp_image(base64_content: String, extension: String) -> Result<String, String> {
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_content.trim())
        .map_err(|e| e.to_string())?;
    let ext = if extension.is_empty() { "png".to_string() } else { extension };
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let path = std::env::temp_dir().join(format!("mahi-vision-{}-{}.{}", std::process::id(), nanos, ext));
    fs::write(&path, bytes).map_err(|e| e.to_string())?;
    Ok(path.to_string_lossy().to_string())
}

/// Deletes a temp image previously created by save_temp_image. Best-effort:
/// only paths inside the OS temp dir whose file name matches our own
/// "mahi-vision-" prefix are removable, so a stray/malicious path can't be
/// used to delete arbitrary files. A missing file is treated as success.
#[tauri::command]
pub fn delete_temp_image(path: String) -> Result<(), String> {
    let p = std::path::Path::new(&path);
    let in_temp = p.starts_with(std::env::temp_dir());
    let named_ours = p
        .file_name()
        .and_then(|n| n.to_str())
        .map(|n| n.starts_with("mahi-vision-"))
        .unwrap_or(false);
    if !in_temp || !named_ours {
        return Err("refused: not a MAHI temp image path".into());
    }
    match fs::remove_file(p) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.to_string()),
    }
}
