use base64::Engine;
use std::fs;
use std::time::{SystemTime, UNIX_EPOCH};

/// Decode base64 media (generated by an agent tool call) and write it to a
/// workspace-relative path. Kept separate from write_file because the
/// content here is binary, not UTF-8 text.
#[tauri::command]
pub fn write_file_binary(
    workspace: String,
    path: String,
    base64_content: String,
) -> Result<(), String> {
    let p = crate::resolve(&workspace, &path)?;
    crate::ensure_not_workspace_root(&workspace, &p)?;
    if let Some(parent) = p.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_content.trim())
        .map_err(|e| e.to_string())?;
    fs::write(p, bytes).map_err(|e| e.to_string())
}

/// Decodes a base64 image and writes it to the OS temp directory, returning
/// the absolute path — used when the active provider/model can't accept
/// image content directly in chat messages (see agent.ts's supportsVision
/// gating), so the path can be handed to a vision-capable MCP tool instead.
#[tauri::command]
pub fn save_temp_image(base64_content: String, extension: String) -> Result<String, String> {
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_content.trim())
        .map_err(|e| e.to_string())?;
    let ext = if extension.is_empty() { "png".to_string() } else { extension };
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let path = std::env::temp_dir().join(format!("mahi-vision-{}-{}.{}", std::process::id(), nanos, ext));
    fs::write(&path, bytes).map_err(|e| e.to_string())?;
    Ok(path.to_string_lossy().to_string())
}
