use base64::Engine;
use std::fs;

/// Decode base64 media (generated by an agent tool call) and write it to a
/// workspace-relative path. Kept separate from write_file because the
/// content here is binary, not UTF-8 text.
#[tauri::command]
pub fn write_file_binary(workspace: String, path: String, base64_content: String) -> Result<(), String> {
    let p = crate::resolve(&workspace, &path)?;
    if let Some(parent) = p.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_content.trim())
        .map_err(|e| e.to_string())?;
    fs::write(p, bytes).map_err(|e| e.to_string())
}
